spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_storage
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9094

app:
  kafka:
    topic-replicas: 1
  workers:
    msisdn-data-sync-pool: 2
    msisdn-data-sync-batch: 10000
    msisdn-data-sync-lag-hours: 24
    mnp-data-comparison-pool: 10
    mnp-data-comparison-batch: 10000
  zniis-connector-url: http://localhost:8090
  mnp.source: filesystem