logging:
  level:
    root: INFO

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: app-db-pool
      minimum-idle: 10
      maximum-pool-size: 25
      connection-test-query: select 1
  thymeleaf:
    mode: text
    suffix: .sql
    prefix: classpath:/sql/templates/
    view-names: '*-tpl'
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
  task:
    scheduling:
      pool:
        size: 3
  liquibase:
    change-log: db/changelog/sync-service.yaml

app:
  kafka:
    topic-replicas: 3
    msisdn-data-sync-topic:
      name: sim-cards-data
      partitions: 30
  sync-request-executors-pool: 3
  mnp.source: sftp

info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@